### ISSUE TITLE
Suggestions for Types proposal

### ISSUE THREAD

**Issue by czender** [diwg/cf2#9]
Daniel,
Here are my initial suggestions for the Types proposal. If you find they have merit, please craft the replacement language yourself as I am short on time this week:
1. List NC_UBYTE among the new atomic types
2. This statement

> enum types may be used, but only if they resolve to an atomic external type at the end.

needs elaboration. I think that netCDF4 library ensures that the base type of an enum must be an integer. If so, then the statement is redundant, since all integer types are valid base types. What does "at the end" add to the sentence? Since the base type must be an integer, there can be no recursive ENUM variables (yes?).
3. It's unclear why you narrow the proposal down to just adding ENUM, not VLEN, COMPOUND, or OPAQUE. This means the Types proposal  is in effect a proposal to allow ENUM and STRING types (so should the name be changed?), because the integer types are covered by my CF1 proposal which languishes in limbo but will probably be adopted eventually (and does anyone recall another CF1 proposal to allow STRING?) . Please add rationale and/or explanation why the proposal is narrow, since adoptees will likely want to understand this proposal in the context of previous and potential future proposals related to types.

**Comment by ghost** [comment]
> I think that netCDF4 library ensures that the base type of an enum must be an integer.

What we are talking about here is the HDF5 Enumeration datatype (`H5T_ENUM`) whose elements represent named integer values called members or enumerators. Currently, only ASCII names are supported.

**Comment by czender** [comment]
I think Daniel needs to chime in as to his intentions about this. Non-ASCII member labels are legal in netCDF4, and I see no reason to exclude them from this proposal. This CDL shows what I mean. 

```
netcdf enum {

 types:
   ubyte enum enum_ubyte_t {Clear=0,Cumulonimbus=1,Stratus=2,Missing=128};
   short enum enum_sht_t {Small=-32000,Medium=0,Large=32767,missing_value=-32768};
   uint64 enum enum_uint64_t {Greek_Καλημέρα=0,Japanese_キャク=1,Chinese_龥=3};

 dimensions:
   lon=4;

 variables:
   enum_ubyte_t cld_flg(lon);
   enum_ubyte_t cld_flg:_FillValue=Missing;

   enum_sht_t size(lon);
   enum_sht_t size:_FillValue=missing_value;

   enum_uint64_t language(lon);
 
 data:
   cld_flg=Stratus,_,Cumulonimbus,Clear;
   size=_,Small,Medium,Large;
   language=Chinese_龥,Japanese_キャク,Greek_Καλημέρα,Greek_Καλημέρα;
} // end root group

```

**Comment by erget** [comment]
Responding to @czender 's comments:

1. Of course, this one slipped past me.
1. I think I was just in "overly-restrictive" mode when I was writing this - you're right, netCDF enforces this by itself so there's no need to go over the top. I also have no problem with non-ASCII member labels. IIRC there was a bit of discussion last year at the netCDF-CF workshop after Ethan's presentation on strings that made me a bit nervous about going beyond ASCII, but we can see if discussion about that comes back.
1. I'll add a bit of background in the next commit. Basically, my intent with this proposal is to get something passed through that's as noncontroversial as possible, because EUMETSAT definitely intends on using these data types. IMHO VLEN, COMPOUND and OPAQUE are all interesting but a whole different can of worms.

Another alternative would be to try to revive @czender 's [proposal](https://cf-trac.llnl.gov/trac/ticket/166) in CF1 and make a whole different one to address user-defined data types. I could get on board with that. Since I know that EUMETSAT will be producing data "soon" (2021) using `enum` and the other atomic external types, I'd like to maximize the chances that we can do so in a CF-compliant fashion beforehand.
